apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: standard
  hostPath:
    path: '/var/lib/postgresql/data'
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce